### ISSUE TITLE
Block 301 headers when error headers exist

### ISSUE THREAD

**Issue by mingard** [dadi/web#100]
When an event error is captured, a 404 header is set e.g.
```JSON
{
  "name":"dadi-web",
  "hostname":"ip-172-31-41-240",
  "pid":20959,
  "level":50,
  "module":"event",
  "msg":"{ [TypeError: Cannot read property 'urls' of undefined] statusCode: 404 }",
  "time":"2016-12-01T12:10:05.507Z",
  "v":0
}
```

If another event calls a 301
```javascript
res.writeHead(301, {Location: redirect_url})
```
The error *Error: Can't set headers after they are sent* is output. 

In this instance, no further headers should not be sent. Perhaps a warning instead? @jimlambie thoughts?

**Comment by jimlambie** [comment]
@mingard please either attach the event files in question or send link to a repo where this is a problem.

**Comment by mingard** [comment]
@jimlambie the only repo with this issue has been sorted with better error handling, however I will setup a temporary repo to demo. Might be worth keeping a **web-bugs** playground repo with branches for bugs.

**Comment by jimlambie** [comment]
I don't see that we can do anything here, other than implement better event error handling (see #98). If an event calls res.writeHead, Web has already lost control over the sending of the response.

I'd suggest that unit tests be added to projects...

**Comment by mingard** [comment]
Agree
