### ISSUE TITLE
Should API be enabled by default?

### ISSUE THREAD

**Issue by adamkdean** [dadi/web#109]
The most basic configuration we can have is:

```
 {
   "app": {
     "name": "DADI Web MD"
   },
   "server": {
     "host": "127.0.0.1",
     "port": 3000
   },
   "api": {
     "enabled": false
   }
 }
```

Should API need to be disabled? Shouldn't we enable it if we want to use it, either with `enabled: true` or simply by supplying configuration?

**Comment by eduardoboucas** [comment]
Nothing against that, but this would be a breaking change that should go in the next major release. Some sites rely on the fact that API access is enabled by default and their `api` block contains just the API details — these would break. 💀

**Comment by jimlambie** [comment]
@eduardoboucas would this be a breaking change? If sites are supplying an API  block and expecting it to be enabled, isn't what @adamkdean is suggesting essentially the same?

**Comment by adamkdean** [comment]
That was my thinking, if a block is supplied, we can enable it implicitly.

**Comment by eduardoboucas** [comment]
The current default of `api.enabled` is `true`, which I believe is what @adamkdean is looking to change. If that's the case, imagine the following config:

```json
"api": {
  "host": "myapi.com",
  "protocol": "https",
  "port": 80
}
```

This omits the `enabled` property as it's enabled by default. If you change that, the block would lead to a disabled API.

Unless something is being lost in translation?

**Comment by eduardoboucas** [comment]
I see what you mean. You want to get rid of `api.enabled` altogether and enable API if a block is supplied?

The problem with that is you can't quickly toggle an API on or off, you have to remove the entire block, store the credentials somewhere temporarily and then add everything back in if you want to enable again.

**Comment by jimlambie** [comment]
Solid answer. That's why it was there :)

**Comment by jimlambie** [comment]
@adamkdean ok to close until we discover if it's really an issue?

**Comment by adamkdean** [comment]
Yes, I'm satisfied with the responses! 🙇
