### ISSUE TITLE
Allow multiple partial paths to be passed in the config

### ISSUE THREAD

**Issue by abovebored** [dadi/web#117]
Allow the specification of multiple partial paths. i.e., 

```JSON
"paths": {
    "partials": [
        "./workspace/partials",
        "../../frontend-system"
    ]
}
```

The above modification will allow referencing a folder outside the `/workspace/` location. 

This could be then used in the Dust templates like so:

`{>"../../frontend-system/gallery"/}`

Or...

`{>"workspace/frontend-system/gallery"/}`

P.S. I imagine it would be a similar amount of work to extend this to all the `paths` options?

**Comment by jimlambie** [comment]
@abovebored this can be done, but prefix for the partials will be the last part of the path, e.g.

```
"paths": {
    "partials": [
        "./workspace/partials",
        "../../frontend-system"
    ]
}
```

`{>"partials/gallery"/}`
`{>"frontend-system/gallery"/}`

Does that sound reasonable?

**Comment by abovebored** [comment]
Yes, perfect @jimlambie
