### ISSUE TITLE
Add postinstall script to copy a config file 

### ISSUE THREAD

**Issue by jimlambie** [dadi/web#120]
DADI Web requires a config file in a /config directory in the installation. This package should have a postinstall script to handle that.

**Comment by adamkdean** [comment]
What should the content of that config file be?

**Comment by jimlambie** [comment]
For reference:
* https://github.com/dadi/api-filestore/blob/master/package.json#L9
* https://github.com/dadi/api-filestore/blob/master/scripts/copy-config.js
