### ISSUE TITLE
Update sample-workspace

### ISSUE THREAD

**Issue by abovebored** [dadi/web#133]
We should update the `sample-workspace` to relate to the latest concepts and config formats. We can also add a 'boot page' to introduce people to _Web_.

Thoughts:

- We'll need a postinstall script for npm users which copies `sample-workspace` to their install directory and renames it `workspace` (then boots the app).

![slack-imgs](https://cloud.githubusercontent.com/assets/649231/23909774/9308530a-08cf-11e7-993e-1dd48231dd5e.png)

- Shall we make the default workspace a very basic blog using our new markdown datasource?

**Comment by abovebored** [comment]
Should the folder `sample-workspace` be renamed to `workspace` (with appropriate config.development.json) so the app will boot easily if you download a release not from NPM?

**Comment by adamkdean** [comment]
I like this idea, especially with the boot page.
