### ISSUE TITLE
Profiling and debugging

### ISSUE THREAD

**Issue by abovedave** [dadi/web#141]
I’m thinking of a tool we can use to optimise `Web` (accessible through `?profile=true`) where we can see all the data on the page (similar to `?json=true`) compared with the variables present in the dust templates. For example:

In a posts.json:

```
{
    "datasources": [
        "posts"
    ]
}
```

In a page.dust:

```
{#post}
   {title}
   {body}
{/post}
```

In the `data` block:

```
{
    "post": [
        "title": "Hello",
        "body": "Copy goes here",
        "tags": []
        "author": "Jim"
    ]
}
```

In ?profile=true

```
You could optimise XX% in rendering data by adding the following to the datasource `posts`:

"fields": {
    "title": 1,
    "body": 1
}
```

UI could take inspiration from Safari

![screen shot 2017-03-30 at 09 47 46](https://cloud.githubusercontent.com/assets/649231/24495847/5eb15a0a-152e-11e7-99d5-0790548a60bd.png)

**Comment by abovebored** [comment]
In addition this tool could be incorporated somewhere for testing paths?

http://forbeslindesay.github.io/express-route-tester/

**Comment by abovebored** [comment]
Note to self: [sitespeed.io](https://www.sitespeed.io/)
