### ISSUE TITLE
Github RSS feed not working

### ISSUE THREAD

**Issue by abovebored** [dadi/web#159]
<img width="319" alt="screen shot 2017-04-20 at 11 03 27" src="https://cloud.githubusercontent.com/assets/649231/25225352/07c0c96a-25b9-11e7-99cf-9ec9c5622c63.png">

**Comment by jimlambie** [comment]
@abovebored this appears to work fine, have sent PR to related project

**Comment by jimlambie** [comment]
@abovebored I believe this can be closed now?
