### ISSUE TITLE
Handle pages and partials directories

### ISSUE THREAD

**Issue by eduardoboucas** [dadi/web#163]
## The problem

We have a clear distinction between a page and a partial: the former has a schema and creates a route, whereas the latter doesn't. In addition to this, we're also separating them into two different directories, sitting at the same level within workspace.

```
workspace/
├─┬ pages/
│ ├── about.dust
│ └── index.dust
└── partials/
  ├── footer.dust
  └── header.dust
```

If we want to include `about.dust` from `index.dust`, we'd do `{> "about" /}`. But if we want to include `footer.dust` on the same file, we'd do `{> "partials/footer" /}`. This relationship between the paths of the host file and the included files is incorrect, as it makes it seem like `footer` is in a sub-directory called `partials` relatively to where `index` is.

This is something we create artificially when registering Dust partials, by prepending the string `partials/` to the name of each partial. Dust gives us the power to do this, other engines won't.

Take [Pug](https://github.com/pugjs/pug), for example. You need to tell it what base directory to use when including files. Using our currently directory structure, we can either set it to be `pages/`, which means we won't be able to include anything from `partials/`, or we set it to `partials/`, which would mean we won't be able to include anything from `pages/`.

Furthermore, this is how an include would look if we go with `partials/` as the base directory:

```
include /footer.pug
```

There's no mention of `partials/` in the include because, again, that's a sub-directory that doesn't exist. It was created artificially for Dust partials.

## Solution 1: Merge pages and partials into one directory

One solution would be to place all templates under the same base directory (could still be called `pages/`). Inside, we'd still have pages, which would be identified by having a JSON schema file, as well as any other templates (effectively partials), optionally inside sub-directories that go as deep as necessary.

This would allow us to actually create the hierarchy that we're artificially creating with Dust, by having a `partials/` sub-directory. It'd look something like:

```
workspace/
└─┬ pages/
  ├── partials/
  |  ├── footer.dust
  |  └── header.dust
  ├── about.dust
  └── index.dust
```

When including templates in Dust, nothing would change. But because we can set the `pages/` directory as the base path, we can have a consistent behaviour across all engines.

*Dust:*
```
{> "partials/footer" /}
```

*Pug:*
```
include /partials/footer.pug
```

For our current clients, the only migration step necessary would be to move the `partials/` directory inside `pages/` and everything would still work the same.

## Solution 2: Leave everything as is

We can leave everything as is and accept that different template engines will have different behaviour when it comes to including partials. The paths may be different across engines and, in some cases, we will only be able to include part of the templates.

If we're happy with this and we document everything properly, it's not a terrible thing to have. I just wanted to flag this so we're all aware of the problem and decide if we want to take the opportunity of releasing 3.0 to change that.

@jimlambie @abovebored any thoughts? Let me know if any of this isn't clear.

Thanks! ❤️

**Comment by jimlambie** [comment]
I like option 1 - it's not a massive migration path to move a directory. We can load partials in subdirectories currently as well, perhaps we should be able to do the same for pages?

For example, WC has a lot of files in the `pages` directory - it'd be nice to split them into subdirectories. In that scenario, how would partials (specifically global partials) work?

**Comment by eduardoboucas** [comment]
Indeed, we could also allow pages to be in subdirectories. As long as they have a JSON schema file, we can clearly identify them (to make sure: it is currently a requirement that pages have a JSON file, right?).

I believe pages have a default route at the moment, so if you don't specify their path in the `routes` property, they assume a route with the name of the page (e.g. `test.json` becomes `/test`). In this scenario, would you expect a page on a sub-directory to have that hierarchy reflected in the route? So, would a page at `subdir/test.json` have a default route of `/subdir/test` or still `/test`?

As for partials, it would depend on the template engine, as some support includes with relative paths (like Pug) and others only support absolute paths (like Dust). Take the following example where we multiple sub-directories with partials and pages:

```
workspace/
└─┬ pages/
  ├── partials/
  |  ├── footer.dust
  |  └── header.dust
  ├── sub-dir/
  |  ├── more-partials/
  |  |  └── nav.dust 
  |  └── products.dust  
  ├── about.dust
  └── index.dust
```

You can always specify the absolute path from the `pages` directory. So if you wanted to include `footer.dust` from `products.dust`, you'd use:

```
{> "partials/footer" /}
```

If you wanted to include `nav.dust` from `products.dust`, you can still use the absolute path:


```
{> "sub-dir/more-partials/nav" /}
```

With Pug, you'd also have the option to specify a relative path:

```
include more-partials/nav.pug
```

Does that make sense?

**Comment by jimlambie** [comment]
@eduardoboucas interesting question re directory structure and routing. I think the default route could definitely be derived from the directory hierarchy

**Comment by eduardoboucas** [comment]
This has been incorporated into #166, so I'll close this one.
