### ISSUE TITLE
Introduce brotli compression

### ISSUE THREAD

**Issue by mingard** [dadi/web#174]
Brotli is an alternative compression that provides, in real world testing, around 20% smaller payload than gzip.
useful package: https://www.npmjs.com/package/brotli
useful resources: 
https://css-tricks.com/brotli-static-compression/
https://engineering.linkedin.com/blog/2017/05/boosting-site-speed-using-brotli-compression
https://hacks.mozilla.org/2015/11/better-than-gzip-compression-with-brotli/

Also applicable to CDN.

A potentially significant performance increase with a minor technical overhead.

Thoughts please.

**Comment by jimlambie** [comment]
We'd need to add this as an alternative, rather than a replacement, right? Based on whatever the browser sends in the accept header?

**Comment by jimlambie** [comment]
We also need to think about how this would work with it: https://github.com/dadi/web/issues/158

That issue suggests we should compress before caching, as the compression is an expensive operation. If we have two types of compression possible, we can't really store the compressed response (unless we key the cached item with it's compression type)

**Comment by mingard** [comment]
>We'd need to add this as an alternative, rather than a replacement, right? Based on whatever the browser sends in the accept header?

Yes, it'd be an alternative.

> unless we key the cached item with it's compression type

Yes, that's an interesting obstacle. Caching with a key seems like an elegant solution.

**Comment by abovebored** [comment]
I've implemented br already in #167 for assets, so I happy to add it to the page response too in that PR 👍

I'm also floating the idea of deprecating `config.headers.useGzipCompression` and adding `config.headers.useCompression` in there to cover this change.

> That issue suggests we should compress before caching, as the compression is an expensive operation.

That's an interesting idea of pre-compression, which nobody is really doing. Would be nice with assets also - although that sounds like something to roadmap as it's more complex? We have our cache headers in order so this only affects first response.

**Comment by mingard** [comment]
`config.headers.useCompression` 👍 

I have some ideas for page pre-compression. I'll try and summarise in a concept issue

**Comment by abovebored** [comment]
Nice @mingard: if you can think about assets to that can feed into CDN methodology 🌮
