### ISSUE TITLE
Check for existing setup before creating new files

### ISSUE THREAD

**Issue by eduardoboucas** [dadi/web#180]
When Web is installed as a dependency via npm, there's some stuff that is copied to the directory (configs, workspace directory, bootstrap file). While this is great, it has caused some confusion for me a couple of times when adding/upgrading Web in an existing project.

For example, in a project I already had a `main.js` file that was attached to `npm start`. As soon as I upgraded Web to the latest version, it added a `server.js`.

Before copying any files, could we first check for signs that the project has already been set up? For example, we could check for a `config/` directory and not copy any files if it exists.

I think it's great that this functionality exists, allowing people to have a skeleton ready as soon as they install the app for the first time, but ideally it wouldn't introduce any unnecessary noise to existing projects.

Any thoughts @jimlambie @abovebored?

Thanks! ❤️

**Comment by abovebored** [comment]
It does this check already for workspace & config, so we could add the `server.js` into there too (maybe look for index.js & main.js?)

The thinking behind it was to make sure there was one less step in setup - adding an `npm start` script as [npm start](https://docs.npmjs.com/cli/start) runs `server.js` by default.

**Comment by abovebored** [comment]
Closing. We've  moved it to [dadi/cli](https://github.com/dadi/web)
