### ISSUE TITLE
3.0 Routing bug

### ISSUE THREAD

**Issue by abovebored** [dadi/web#190]
I have a liberal route for a page which all sections could match:

```JSON
"routes": [
    {
      "path": "/:section/"
    }
]
```
However the (static) datasource should use `section` to filter the results:

```JSON
"requestParams": [{
    "param": "section", "field": "handle"
}]
```

This works as expected in 2.0, but in 3.0 instead this liberal route is resulting in the same page being displayed on every URL (homepage routing is ok, as is `/:foo/:bar/` routing.

**Comment by jimlambie** [comment]
`static`, not `markdown` provider?
