### ISSUE TITLE
Clear up confusion between page.key and page.name

### ISSUE THREAD

**Issue by abovedave** [dadi/web#202]
It seems we have potentially two configuration options doing similar things in the page specification.

To investigate:

https://github.com/dadi/web/blob/0fbaced457ce41390d32c8ae980683027ee5db6a/dadi/lib/index.js#L732-L736

https://github.com/dadi/web/blob/1255df397e67b1c574d5cb23586909dd41309e48/dadi/lib/page/index.js#L12-L13

Consider making the fallback here the filename:

https://github.com/dadi/web/blob/1255df397e67b1c574d5cb23586909dd41309e48/dadi/lib/page/index.js#L50

**Comment by mingard** [comment]
@abovebored The difference between `key` and `name` exists because of a project requirement where a dust helper needed to be able to refer to a page by a short key, but the name of the page was to remain relatively long.

**Comment by jimlambie** [comment]
@abovebored Yes @mingard is right, the `key` property was introduced for the @url Dust helper. The `getComponent` method was introduced purely for that helper as well. 

`name` remains the most useful identifier of the page, as you can see it is used in datasources, events, controllers...

I'm up for modifying these properties if required. Datasources also use `key` and `name`, but perhaps it ought to be `key` + `description` ?

**Comment by abovebored** [comment]
Thanks guys, very useful. 

[This is the `@url` helper for reference](https://github.com/dadi/dustjs-helpers/blob/master/dadi-dustjs-helpers.js#L358-L388).
