### ISSUE TITLE
Fragment caching

### ISSUE THREAD

**Issue by abovedave** [dadi/web#206]
A way to exclude page elements from the cache would be very useful e.g., user account information.

Varnish is using [Edge side includes](https://varnish-cache.org/docs/3.0/tutorial/esi.html), which has an [official spec](https://www.w3.org/TR/esi-lang) - could be a good place to start.

**Comment by jimlambie** [comment]
This is going to involve being able to ask Web to fetch/execute a subset of a page's datasource and events, right?

**Comment by abovebored** [comment]
Yes, that cold be one way to do it. Perhaps we might want extend partials to have their own page-style specification.
