### ISSUE TITLE
Too many connections to Redis

### ISSUE THREAD

**Issue by fra967** [dadi/web#229]
Under load Web instances are actively holding thousands of Redis connections open.

Seen with Web 1.11.2 and Web 3.0.x

**Comment by jimlambie** [comment]
Patches for version ranges 1.x, 3.x, 4.x: #233,  #234 , #236 

cc @fra967 @feroviktor

**Comment by jimlambie** [comment]
Resolved in latest published versions of Web: 1.11.4, 3.1.1, 4.0.2
