### ISSUE TITLE
Option to choose whether logs are in text or json format

### ISSUE THREAD

**Issue by fra967** [dadi/web#28]
When troubleshooting production environments, under pressure and with limited bandwidth / time, it's key to process the log files with standard linux command-line tools. 
So it would be great to have a configuration option so that log files can be in text instead of json

**Comment by jimlambie** [comment]
The log module uses standard JSON objects. To transform the logs to text format I recommend installing the Bunyan CLI globally and using that as part of your log processing.

https://github.com/dadi/web/blob/docs/docs/logging.md#viewing-the-logs
https://github.com/trentm/node-bunyan#cli-usage

**Comment by fra967** [comment]
thanks for the info; the thing is that when you are on a shaky mobile connection, even adding a pipe to another command can be a challenge 

anyway, solved with this
```$ cat .bash_aliases 
jtail() { tail "$@" | bunyan; }
jgrep() { grep "$@" | bunyan; }
```
