### ISSUE TITLE
Detect and parse encoded form data

### ISSUE THREAD

**Issue by mingard** [dadi/web#280]
I've been using [multiparty](https://www.npmjs.com/package/multiparty) to detect and decode `multipart/form-data` form data in events. It would be nice to be able to parse form data, and file binaries without needing extra packages.

There are some pretty simple form data decoding methods out there, and probably no need to add a dependency. It'd be nice to cover `application/x-www-form-urlencoded` which is the best enctype to use when the content is strictly alphanumeric (no files or other binaries).

**Comment by jimlambie** [comment]
```
  // add parsers
  app.use(bodyParser.json())
  app.use(bodyParser.text())
  // parse application/x-www-form-urlencoded
  app.use(bodyParser.urlencoded({ extended: true }))
```

😂

**Comment by abovebored** [comment]
Is this related to #170?

**Comment by mingard** [comment]
@jimlambie Perhaps I'm missing something. I couldn't get a result without using another package in the event.

**Comment by jimlambie** [comment]
@mingard what I mean is that `application/x-www-form-urlencoded` is already handled.

If you post, the req.body will contain data from the form:

```
req: {
  body: {
    email: 'jameslambie@gmail.com'
  }
}
```

**Comment by jimlambie** [comment]
And yes, this is the same as #170, closing.

**Comment by mingard** [comment]
Okay thanks.
