### ISSUE TITLE
Page filter is modified by previous (and separate) requests

### ISSUE THREAD

**Issue by fra967** [dadi/web#29]
Browse to http://test.lifestyle.one/whatever/   (make up your own URL so you get a 404)
Kill the browser session
Now browse to a valid page, for example
http://test.lifestyle.one/grazia/
you still get a 404

Clearing cache in both Web and Api doesn't bring any change, you still get the 404 for that valid page.
Restarting dadi-web service brings back the valid content associated to that page, but then the opposite problem appears, i.e. a 404 page (just make up another URL) will always show the valid page.

In short it seems there is some state being kept between different HTTP sessions, and not related to cache (the problem happens whether cache is off or on).

In the API calls for the first example, the filter gets set to "whatever" in all successive calls, even those 
for /grazia, and that explains the 404.

So it appears that filter is not reset and re-uses the last used value, by any request.
The problem has also been reproduced by two totally different browser sessions on different devices and networks.

The use of referer (which should in any case be avoided) on Lifestyle may contribute to this problem, so this issue needs further investigation (such as reproduce it with no referer logic being used).

However, given the critical nature of the problem, I prefer to raise it in case somebody is aware of any state being preserved between HTTP sessions. 

More details soon.

Version:     1.0.3  (npm.dadi.tech)
Node.JS:     0.12

**Comment by jimlambie** [comment]
Fixed by https://github.com/dadi/web/commit/340f557a8a8ca84d81fdf8e3fe2b45f88daa21de
