### ISSUE TITLE
Modifying datasource endpoints before execution

### ISSUE THREAD

**Issue by jimlambie** [dadi/web#296]
Many remote APIs require parameters to be included in the endpoint path, rather than in the querystring.

In the current version of Web, we can use requestParams (parameters extracted from the URL) to modify an endpoint, but in some cases it's required to modify an endpoint using data previously fetched.

Rather than extend the requestParams functionality, I think we need something akin to filterEvent to allow modifying the endpoint from an event.

This is somewhat similar to @adamkdean's issue: https://github.com/dadi/web/issues/216

Perhaps both chaining _and_ modifying via an event should be possible.

**Comment by abovedave** [comment]
What about this principal (doesn't have to be executed this way):

|`source` | Desc. |
|---|---|
|`request` | default, as it is now |
| `session` | retrieves values stored in the `req.session` |
| `global` | retrieves values stored in the config file (tokens, urls etc |

```
{
  "datasource": {
    "key": "foo",
    "name": "",
    "source": {
      "type": "remote",
      "protocol": "http",
      "host": "bar.com",
      "endpoint": "/{token}/{user}/{title}/"
    },
    "auth": false,
    "requestParams": [
      {
        "param": "token",
        "field": "token",
        "source": "global",
        "target": "endpoint"
      },
      {
        "param": "user",
        "field": "user",
        "source": "session",
        "target": "endpoint"
      },
      {
        "param": "title",
        "field": "title",
        "source": "request",
        "target": "endpoint"
      }
    ]
  }
}
```

**Comment by jimlambie** [comment]
I like that, very tidy. Makes getting config values out easier. Perhaps we make it `"source": "config"` and use the `param` argument to specify the path to the config property.

It'd be nice to build in both event and chaining functionality too, as we do for the filter object currently.
