### ISSUE TITLE
Modifying events at run-time breaks middleware app routing

### ISSUE THREAD

**Issue by adamkdean** [dadi/web#339]
This is a very strange bug. If you modify an event while Web is running, middleware app routing, i.e. `app.use('/route', () => {})` within middleware stops working, though `app.use(() => {})` continues to work.

To recreate, simply create a middleware which adds a route handler, and then at run-time, change an event, and then try and hit that endpoint again. In this case, it was a `POST /login` that wouldn't fire.

**Comment by abovedave** [comment]
I'm having trouble replicating this one @adamkdean, what was in the event and middleware that might be influencing this?

**Comment by adamkdean** [comment]
I don't recall. If I encounter it again, or dig it out, I'll re-open.
