### ISSUE TITLE
Simplify connection to multiple APIs

### ISSUE THREAD

**Issue by abovedave** [dadi/web#359]
Config to match the circa 4x refactor of datasources:

Existing

```json
"api": {
  "enabled": true,
  "host": "127.0.01",
  "port": 3001
},
"auth": {
  "tokenUrl": "/token",
  "clientId": "xxxxx",
  "secret": "xxxxx"
}
```

Proposal

```json
"credentials": [
  {
    "alias": "main",
    "type": "dadiapi",
    "enabled": false,
    "host": "127.0.01",
    "port": 3001,
    "auth": {
      "tokenUrl": "/token",
      "clientId": "xxxxx",
      "secret": "xxxxx"
    }
  },
  {
    "alias": "blog",
    "type": "wordpress",
    "auth": {
      "bearerToken": "xxxxx"
    }
  }
]
```

This would facilitate easy reuse of credentials across datasources e.g., 

```json
{
  "datasource": {
    "key": "latest-posts",
    "source": "blog"
    ...
  }
}
```
We could also make these available to events and middleware.

NB Consider backwards compatibility with old style config

**Comment by jimlambie** [comment]
@abovedave could we use "source" instead of alias in the datasource? then it matches with the "source" block when not using an alias, however we'd test for string vs object?

**Comment by abovedave** [comment]
Excellent idea @jimlambie. We could even make it override any values from the `global.creds` that are passed in the `datasource.source`.

**Comment by abovedave** [comment]
I've updated the example to reflect that.
