### ISSUE TITLE
Missing .ico in debug view

### ISSUE THREAD

**Issue by mingard** [dadi/web#387]
Currently .ico files aren't appearing in debug view. This _could_ be pulled from the project .ico, or be the DADI logo.

![screen shot on 2018-05-08 at 21_46_14](https://user-images.githubusercontent.com/1352469/39782312-b5ee67a8-5309-11e8-850b-a1a3f79241fe.png)

**Comment by jimlambie** [comment]
I think using the DADI logo would be nice, but does that confuse the browser if we reference different icons for the same url?
