### ISSUE TITLE
Loading rewrites disables page cache

### ISSUE THREAD

**Issue by abovedave** [dadi/web#399]
Load Web with a basic configuration:

```json
{
  "server": {
    "host": "127.0.0.1",
    "port": 3001
  },
  "cluster": false
}
```

`npm start` and visit a route a few times, observe the request headers:

```
Cache-Control: public, max-age=86400
Connection: keep-alive
Content-Encoding: br
Content-Length: 461
Content-Type: text/html
Date: Fri, 25 May 2018 13:34:20 GMT
ETag: W/"1cd-16397801258"
X-Cache: HIT
X-Cache-Lookup: HIT
```

Then add a `rewrites` block to the config.json

```
{
  "server": {
    "host": "127.0.0.1",
    "port": 3001
  },
  "cluster": false,
  "rewrites": {
    "path": "./workspace/routes/rewrites.txt"
  }
}
```

Reload the app then observe page headers again:

```
Connection: keep-alive
Content-Encoding: br
Content-Length: 461
Content-Type: text/html
Date: Fri, 25 May 2018 13:35:56 GMT
```

DADI Web 6.0.0 
Node.js 8.9 
NPM 6.1.0

**Comment by abovedave** [comment]
This returns `undefined` when `rewrites` is in the config:

https://github.com/dadi/web/blob/develop/dadi/lib/cache/index.js#L59

**Comment by jimlambie** [comment]
@abovedave what is the URL being used to test the above?

**Comment by abovedave** [comment]
I'm using this, but also can recreate with a blank `rewrites.txt` file:

```
\/join$ /en/#join [R=302,NC,L]
```
