### ISSUE TITLE
Dependency in maintenance

### ISSUE THREAD

**Issue by jimlambie** [dadi/web#447]
The circular-json dependency reports it is in maintenance and a new module should be used in its place:

```
> circular-json@0.5.7 postinstall /dadi/sandbox/web/node_modules/circular-json
> echo ''; echo "\x1B[1mCircularJSON\x1B[0m is in \x1B[4mmaintenance only\x1B[0m, \x1B[1mflatted\x1B[0m is its successor."; echo ''

\x1B[1mCircularJSON\x1B[0m is in \x1B[4mmaintenance only\x1B[0m, \x1B[1mflatted\x1B[0m is its successor.
```

**Comment by jimlambie** [comment]
@philip-hunt remind me where we use the current circular-json dependency, and I may be able to confirm. I believe circular-json returns the same sort of response, doesn't it? The idea is to not keep adding nested objects, and rather stop the tree building by adding a string to say "I'm not repeating myself"

**Comment by philip-hunt** [comment]
@jimlambie yes I believe that is correct, it's used just before we output a json response here: https://github.com/dadi/web/blob/master/dadi/lib/view/send.js#L19

Here's a comparison of the output formats for both libraries. Both are strings so it wouldn't make sense to try and convert the Flatted output to the original CircularJSON.

CircularJSON: 

{
  "result": "success",
  "message": "Cache cleared successfully"
}

Flatted:

[{
  "result": "1",
  "message": "2"
},"success","Cache cleared successfully"]

**Comment by jimlambie** [comment]
Closed by https://github.com/dadi/web/commit/84bbff3329a3242adac9a5333176d5ea600a35fe, thanks @philip-hunt
