### ISSUE TITLE
Pagination failing when debug is disabled

### ISSUE THREAD

**Issue by adamkdean** [dadi/web#489]
I'm seeing a very strange issue with a blog that uses markdown files and sorts by one of the attributes, where there are 3 pages (of 5 posts) but where the pagination only works properly when debug is enabled.

If you need more info, let me know.

Web `6.1.1`

**Comment by jimlambie** [comment]
This looks like Web ignores querystring parametrs when generating a cache key. I honestly don't recall if this was done for a specific reason.

I wonder if @abovedave or @eduardoboucas might know anything?

**Comment by jimlambie** [comment]
Closed by
