### ISSUE TITLE
External data sources

### ISSUE THREAD

**Issue by abovebored** [dadi/web#52]
I'd like to see support for data sources that are not from [DADI API ](https://github.com/dadi/api/).

Some examples:

### [Twitter](https://dev.twitter.com/rest/public) (OAuth 1.0a)
Display a list of the 10 latest [@dadi](https://twitter.com/dadi) tweets
https://dev.twitter.com/rest/reference/get/statuses/user_timeline

### [Tumblr](https://www.tumblr.com/docs/en/api/v2) (OAuth 1.0a)
Recent posts tagged with `#shillaryclinton`
https://www.tumblr.com/docs/en/api/v2#tagged-method

### [Instagram](https://www.instagram.com/developer/) (OAuth 2.0)
10 recent pictures geotagged in London
https://www.instagram.com/developer/endpoints/media/#get_media_search
`lat=51.5074&lng=0.1278`

More info: [OAuth](http://oauth.net/)

**Comment by abovebored** [comment]
This is interesting: http://passportjs.org/

**Comment by henriquea** [comment]
@abovebored I used passport.js once within a Facebook app. Works well!

**Comment by eduardoboucas** [comment]
I don't think Passport.js is what we're after here, as it's an SSO piece that implements an authentication system in an app using various third parties, and not an authenticator for those third parties APIs.

The only problem I see with integrating with those services is that some of them require 3-legged OAuth, which always requires the user to be redirected to the service to approve the request and then be redirected back to us with an access token — this flow wouldn't work for server-side auth in Web, and any requests to this type of API would have to be handled on a per-app basis.

This will be the case in the vast majority of services when the objective is to act on behalf of a user (e.g. [Instagram](https://www.instagram.com/developer/authentication/).

Alternatively, some services offer a 2-legged OAuth alternative (similar to the authentication method used by DADI API), like [Twitter](https://dev.twitter.com/oauth/application-only), which shouldn't be a problem to integrate directly with Web data sources.

I'm happy to look into this, just wanted to make people aware of potential limitations.

/cc @jimlambie

**Comment by jimlambie** [comment]
@eduardoboucas For cases where we need to obtain a token first, can that be done "offline" and the token added to a configuration setting to enable future communication?

**Comment by jimlambie** [comment]
FYI @adamkdean has started in on this, so please communicate with him anything that pops into your head!

**Comment by eduardoboucas** [comment]
You can obtain the token and add it to the config, but it will expire after an undetermined time.

> Even though our access tokens do not specify an expiration time, your app should handle the case that either the user revokes access, or Instagram expires the token after some period of time. If the token is no longer valid, API responses will contain an “error_type=OAuthAccessTokenError”. In this case you will need to re-authenticate the user to obtain a new valid token.
In other words: do not assume your access_token is valid forever.

(from [here](https://www.instagram.com/developer/authentication/))

One alternative I see is the creation of a middleman, likely in the form of a separate app. This would be configured with one or multiple accounts for different social networks and would poll APIs with a configurable interval — if authentication fails, then the access token has expired so it needs to follow the OAuth flow to request a new one (follow a link, give authorisation and store the new access token).

This would then expose a cached copy of the feeds, behind an authentication system similar to what we already use, making it possible to integrate with Web datasources.

It's probably a big job and not an immediate requirement, just some food for thought. 😄

**Comment by adamkdean** [comment]
After discussing this with @eduardoboucas & @jimlambie, we're going to proceed with supporting third-party sources that offer 2-leg auth, but we'll leave the 3-leg auth for another day, otherwise we would need to implement something much bigger, as Eduardo says, which is out of scope for the time being. 🕚

**Comment by adamkdean** [comment]
I've been looking at this further and playing with various third party APIs, and even Tumblr require a user to be redirected to a page to generate an access token & secret. 

I'm wondering whether it would be worth supporting third-party sources (that require this step) by providing an already generated access token. One one hand: `access tokens do not specify an expiration time` but `your app should handle the case that either the user revokes access, or Instagram (for example) expires the token after some period of time`. On the other hand, we cannot actually generate a token server side without [a bigger feature](https://github.com/dadi/web/issues/52#issuecomment-232608885), and the tokens in practise won't be invalidated unless done so by a user.

_If_ tokens aren't invalidated, would this really be any different to generated say an S3 key and putting that in the config? What are peoples thoughts on this? 😰 😬

**Comment by jimlambie** [comment]
That's true, and we could handle that using environment variables, the same way we do for sensitive data, and the same way Heroku apps and Slack bots are configured. Making an env variable for your token the _only_ way to do it would avoid adding this to config. 

I can see this being useful for a number of things in config actually, as the devs start putting more project-specific properties into the configuration files than we have in the schema.

**Comment by adamkdean** [comment]
I agree. I discussed with Eduardo about injected the access tokens in via env vars, as this would allow extension later for any token management app to restart applications with fresh credentials – if the environment allowed this. It would also mean we are able to support more third-parties.

**Comment by eduardoboucas** [comment]
I just want to reiterate my concerns about storing the bearer tokens, regardless of whether it's in a config or via env vars, because they are supposed to be treated as disposable credentials. We'd be making Web rely on a key that can expire (or be revoked) at any point in time, without us having any control over it.

It'd be like storing and using a bearer token generated by DADI API without having any information about its TTL and just assuming it'll always work.

**Comment by adamkdean** [comment]
This is true. It is something that we need to keep in mind, though I don't think `web` is the right place to handle the auth. If we inject the access token/secret via env vars then in the future we'll be able to extend the management of this without having to modify `web`.

Given that the use case for these data sources is likely going to be applications and not users, the most likely way in which a token would be invalidated would be if the user (who would be the website operator perhaps?) revoked it. I completely agree though that we need to bear in mind that there would be risk involved.

I think the web should support third parties from just their access tokens, but I also think that we should think about how we'll monitor, refresh, and provide them.

**Comment by eduardoboucas** [comment]
> Given that the use case for these data sources is likely going to be applications and not users, the most likely way in which a token would be invalidated would be if the user (who would be the website operator perhaps?) revoked it

I think this is assuming a lot. In any case, I'm sure we'll go in the right direction and the call on Monday will help.

**Comment by adamkdean** [comment]
More progress has been made with this. I now have a working version where the `@dadi/api`-style datasources have been abstracted out to `ApiProvider`, but I still need to test various things like caches, chained datasources, etc. 

I think the ability to support external datasources might be separate to each particular implementation of a third party, but something I need to discuss with @eduardoboucas, @mingard, and @jimlambie is how we'll handle things like filtering with third parties. My thoughts are that each datasource provider will parse the filters and construct it's own query for that particular domain.

Anyway, you can see my commits so far for this [here](https://github.com/dadi/web/commits/feature/extensible_datasource) though these are still WIP and messy. Usage [here](https://github.com/adamkdean/dadi-demo-stack/pull/1).

The ApiProvider can be seen [here](https://github.com/dadi/web/blob/feature/extensible_datasource/dadi/lib/providers/api.js).

**Comment by adamkdean** [comment]
The first version of this is now complete with remote, static, and twitter datasource providers. Jim is just making some amendments then we can see what's what and get feedback. 

cc @jimlambie

**Comment by adamkdean** [comment]
For instagram, it is possible to get images without OAuth, like so:

https://www.instagram.com/adamkdean/media/

We could put a simple instagram wrapper around that, for the sake of users displaying images from specific profiles.

**Comment by adamkdean** [comment]
Merged!

https://media.giphy.com/media/l0MYt5jPR6QX5pnqM/giphy.gif
