### ISSUE TITLE
Page.json files with similar routing paths

### ISSUE THREAD

**Issue by abovebored** [dadi/web#58]
The pagination `page` variable defined in a `page.json` are not passed to a datasource when more than one `page.json` have similar routing paths.

For example:

* One page.json has the path `/:category/:subCategory/:title`
* Another has `/:category/:subCategory/:page(\\d+)`
* Visiting `/news/opinion/3/` in my ?json=true query params I see both `title` and `page` defined as `3`

```
"params": {
    "category": "news",
    "subCategory": "opinion",
    "title": "3",
    "page": "3"
},
```

* Even though I see it above, it is not picked up by datasources on the page (should be `"page": 3`):

```
metadata": {
    "limit": 32,
    "page": 1,
    "offset": 0,
    "totalCount": 811,
    "totalPages": 26,
    "nextPage": 2
}
```

Note that `/news/opinion/?page=3` causes the pagination to work, but `title` is still defined in `params`.

**Comment by jimlambie** [comment]
@abovebored this is addressed in the upcoming 1.7.0 release, with a myriad of new ways to avoid routing collisions. I'm going to close this, look out for the release notes with 1.7.0.
