### ISSUE TITLE
CSRF protection

### ISSUE THREAD

**Issue by magnusdahlstrand** [dadi/web#59]
A middleware based approach (using https://github.com/pillarjs/csrf) exposing the CSRF token to the templating layer through a global property or helper.

**Comment by jimlambie** [comment]
@adamkdean another one for you, perhaps have a look at integrating https://www.npmjs.com/package/csurf

**Comment by adamkdean** [comment]
I'll have a look at what @mingard dishes out and see if I will have time for it this coming week :+1: :8ball:

**Comment by adamkdean** [comment]
I can pick this one up now, if that's alright with @mdahlstrand? 😬

**Comment by adamkdean** [comment]
I will be looking at this ticket soon. 🎟

**Comment by adamkdean** [comment]
- [x] add csrf token to view data (https://github.com/dadi/web/commit/0616332a7033ba787c757b07805d6cc9226d2484)
- [ ] catch EBADCSRFTOKEN errors
- [ ] usage example

**Comment by eduardoboucas** [comment]
What's the status on this?

@adamkdean do you need a ✋ ?

**Comment by adamkdean** [comment]
@eduardoboucas I believe I added the CSRF token to the view model, but the validation of the token is still pending. If you have the time to pick this up then that'd be greatly appreciated! Thanks!

**Comment by abovebored** [comment]
BUMP on this.

You seem real close @adamkdean?

**Comment by adamkdean** [comment]
Ah, this hasn't been picked up? I'll find some time this week or next and get this finished.

**Comment by abovebored** [comment]
Many thanks! Some docs would be the icing on the cake too 🍰 

https://github.com/dadi/docs/blob/new/docs/web.md#csrf-tokens

**Comment by adamkdean** [comment]
I do like 🍰.  I'll get you some docs as well. 🙇

**Comment by adamkdean** [comment]
@abovebored take a look and let me know what you think. Have updated the docs also.

🍰 😋 🔏
