### ISSUE TITLE
Protocol level redirect

### ISSUE THREAD

**Issue by feroviktor** [dadi/web#60]
We need a way to redirect pages based on protocol (`http` -> `https` or `https` -> `http`).

For example:
```
https://www.whatcar.com/volvo/s60/saloon/review/in-the-cabin/
-->
http://www.whatcar.com/volvo/s60/saloon/review/in-the-cabin/
```

**Comment by jimlambie** [comment]
@mdahlstrand Wonder if you can take a look at this one for me?
