### ISSUE TITLE
Introduction of a pagination variable

### ISSUE THREAD

**Issue by abovebored** [dadi/web#62]
There's a few use cases where having the `page` variable in a `page.json` route path is causing collisions with other user-defined variables.

Consider this example. We want to show a category index and sub-category index. both with pagination available:

**`category.json`**
``` JSON
 "route": {
    "path": "/:category/:page?"
}
```

**`subcategory.json`**
``` JSON
 "route": {
    "path": "/:category/:subCategory/:page?"
 }
```

A URL such as `/category/2` matches both routings, but `subCategory` would be interpreted as `2`. This works ok when the pages use different datasources, but when they are the same the `requiredDatasource` variable doesn't help direct the query (the model of "if no results found, move to the next routing").

Using traditional GET variables we could do the following without needing to modify the path with the `:page?` addition e.gg., `/news/?page=2`. However there is often an aesthetic requirement to have something like `/news/2`.

The workaround we've been using is to pass regex to the router to identify a `page` variable as only a number, or a article title as a mixed alphanumeric string. I think this is messy and could cause some issue with fringe cases (e.g., below if a subcategory was `sex` 💋  this would fail)

`"path": "/:category/:subCategory([A-Za-z-_0-9]{4,})/:page(\\d+)?/"`

I'm going to use this thread to gather input from SEO specialists, but pending their approval I would like input on the suggestion of changing the following

As paginated pages _do not_ fit the usage for a URL (i.e., /category/article-title will be the same forever, whereas pagination page content /category/2 changes every time a new article is published - all content is pushed down a one position, therefore it is acceptable and logical to introduce a `pagination` fixed variable which is used to indicate where pagination needs to happen. For example:

``` JSON
 "route": {
    "path": "/:category/",
    "paginationVar": "page"
}
```

The URL would be  `/news/page/2`

``` JSON
 "route": {
    "path": "/:category/",
    "paginationVar": "p"
}
```

The URL would be  `/news/p/2`

Etc...

This keeps the pagination variable out the way of the user-define page variables which I think is useful as it is the only real 'special case' variable which is passed to the datasource.

**Comment by mdahlstrand** [comment]
Could we in the page definition support a per-datasource mapping of route parameters to DS params? `dadi/web` would on upstart ensure that parameter mappings are correct.

page.js:
```
"route": {
  "path": "/:category/:page?"
},
"datasources": {
  "categories": {
    "slug": "category",
    "page": "page"
  }
}
```

**Comment by eduardoboucas** [comment]
Can you have a look at #74 please? 👊
