### ISSUE TITLE
SSL support

### ISSUE THREAD

**Issue by josephdenne** [dadi/web#76]
We need integrated support for HTTPS to provide certificate coverage for stand alone instances (outside of a clustered setup where support is offset to a load balancer or proxy.

HTTPS enabled (true/false) and certificate locations (public key, private key, intermediary) should be configurable within the main config file. Certificates should live outside of the main application directory (i.e. include a default location of `/etc/ssl/whatever`).

**Comment by adamkdean** [comment]
Related: https://github.com/dadi/api/issues/119

**Comment by adamkdean** [comment]
@josephdenne how do you want to handle a request on HTTP? Redirect to HTTPS?

**Comment by adamkdean** [comment]
So far no luck in getting a redirect to work on the same port. We could put in a bit of functionality to redirect HTTP to HTTPS when ports are standard, i.e. `http://example.com` would go to 80, we 301 it to `https://example.com` and now it goes to 443. But if a non-standard port is being used then chances are it won't really make much sense to use that. In this case I'd handle redirecting HTTP to HTTPS via nginx or something similar, or...we write something that sits inbetween net.Server and tls.Server, but I think that's overkill.

**Comment by adamkdean** [comment]
This has now been merged. Just need to update the docs.

**Comment by adamkdean** [comment]
All done.
