### ISSUE TITLE
File-based cache performance improvements

### ISSUE THREAD

**Issue by fra967** [dadi/web#82]
When using the file-based cache, the cache directory fills up with thousands of small files, and then the default file-system (ext4) does not perform very well, slowing down when storing more then 5000 files.#
We should document this and propose alternative methods, such as

- periodically clear the cache 
- use a dedicated volume for cache storage, mounted with some specific options (noatime, journalling disabled)

We could also add an option in Web config to choose whether to breakdown cache keys in directories (
`1234/5678/90ab/cdef.json` instead of `1234567890abcdef.json`). This increases the inodes usage but should offer better performance.

**Comment by jimlambie** [comment]
Ref https://github.com/dadi/cache/issues/3, https://github.com/dadi/cache/issues/4

**Comment by adamkdean** [comment]
:+1:

**Comment by adamkdean** [comment]
These are now done in dadi/cache, just need to integrate dadi/cache now.

**Comment by adamkdean** [comment]
🎉
