### ISSUE TITLE
Log rotation hangs the Web process

### ISSUE THREAD

**Issue by fra967** [dadi/web#88]
When log rotation is enabled (for example logging.fileRotationPeriod: "1d" )

a number of ENOENT errors are logged during the rotation, and the Web process hangs for approximately one minute, returning 503 errors

```
web.log.1:[2016-09-02 01:00:00.008] [LOG]   Error: ENOENT, rename '/dadi/web/log/rosecomb.production.log.0'
web.log.1:[2016-09-02 01:00:02.945] [LOG]   Error: ENOENT, rename '/dadi/web/log/rosecomb.production.log.1'
web.log.1:[2016-09-02 01:00:07.256] [LOG]   Error: ENOENT, rename '/dadi/web/log/rosecomb.production.log.2'
web.log.1:[2016-09-02 01:00:11.530] [LOG]   Error: ENOENT, rename '/dadi/web/log/rosecomb.production.log.3'
web.log.1:[2016-09-02 01:00:15.874] [LOG]   Error: ENOENT, rename '/dadi/web/log/rosecomb.production.log.4'
web.log.1:[2016-09-02 01:00:20.171] [LOG]   Error: ENOENT, rename '/dadi/web/log/rosecomb.production.log.5'
web.log.1:[2016-09-02 01:00:24.387] [LOG]   Error: ENOENT, rename '/dadi/web/log/rosecomb.production.log.6'
web.log.1:[2016-09-02 01:00:28.619] [LOG]   Error: ENOENT, rename '/dadi/web/log/rosecomb.production.log.7'
web.log.1:[2016-09-02 01:00:32.853] [LOG]   Error: ENOENT, rename '/dadi/web/log/rosecomb.production.log.8'
web.log.1:[2016-09-02 01:00:37.073] [LOG]   Error: ENOENT, rename '/dadi/web/log/rosecomb.production.log.9'
web.log.1:[2016-09-02 01:00:41.315] [LOG]   Error: ENOENT, rename '/dadi/web/log/rosecomb.production.log.10'
web.log.1:[2016-09-02 01:00:45.538] [LOG]   Error: ENOENT, rename '/dadi/web/log/rosecomb.production.log.11'
web.log.1:[2016-09-02 01:00:49.748] [LOG]   Error: ENOENT, rename '/dadi/web/log/rosecomb.production.log.12'
web.log.1:[2016-09-02 01:00:54.051] [LOG]   Error: ENOENT, rename '/dadi/web/log/rosecomb.production.log'
```

Current work-around is to disable Web log rotation (setting logging.fileRotationPeriod: "" ) and use a logrotate.d config

```
/dadi/web/log/rosecomb.production.log {
    su root root
    daily
    rotate 14
    missingok
    notifempty
    copytruncate
    compress
}
```

This with DADI Web 1.6.7

**Comment by jimlambie** [comment]
@fra967 Please provide the version of both @dadi/web and @dadi/logger installed on this system

**Comment by jimlambie** [comment]
@fra967 nevermind, identified the issue and resolved. Web republished to NPM as 1.6.13

https://github.com/dadi/web/commit/b9346643a6c64878f2f463b97533a8ebb2917e3c

**Comment by jimlambie** [comment]
@fra967 Are you able to confirm if upgrading to 1.6.13 resolves this issue? Has it been encountered since the latest version was published?

**Comment by jimlambie** [comment]
Closed due to inactivity

**Comment by fra967** [comment]
Sorry I have to re-open this, it seems that 1.6.14 does not create ENOENT errors, but does not rotate the log file either.

**Comment by fra967** [comment]
https://github.com/dadiplus/whatcar-com/blob/master/web/config/config.production.json

**Comment by abovebored** [comment]
Closing as this isn't handled anymore. [More info](https://github.com/dadi/logger#log-rotation)
