### ISSUE TITLE
Datasource type: Files

### ISSUE THREAD

**Issue by abovebored** [dadi/web#96]
While developing the [DADI](http://beta.dadi.tech) site, I built a quick way to use use static markdown files (with [Front Matter](https://jekyllrb.com/docs/frontmatter/)) as a datasource. It's pretty rough (an event with no pagination, advanced caching etc). Check it:

https://github.com/dadi/dadi.tech/blob/master/web/workspace/events/insights.js

I'm wondering if this could be a nice extension to datasources the way we have `static` and `remote`. It would also be attractive for people 'graduating up' from a Jekyll site, those not wanting/able to use a database or those who want to use Github as a CMS.

Definition in the `datasource.json` could be:

``` JSON
"source": {
    "type": "files",
    "endpoint": "path/to/folder/on/disk"
}
```

Looking for feedback and leaving a note here for myself to submit a PR for this 😄

**Comment by adamkdean** [comment]
How would this handle sub-directories? Do you have an example of a typical file structure?

Flat-file is a good idea though, think for example, a photo gallery where they might not want the complexity of going through API/CDN.

**Comment by jimlambie** [comment]
Another way to serve files, using @adamkdean's example is to configure a virtual directory and have content served directly from that location on disk. 

It is also possible to create a middleware function that serves content like this. To make this a datasource we'd need to perhaps include a config property for `"type": "markdown"` (for example) so we could include a parser for different file types.

**Comment by adamkdean** [comment]
```
{
  "datasource": {
    "key": "posts",
    "name": "A statically loaded greeting.",
    "source": {
      "type": "markdown",
      "path": "workspace/posts"
    }
  }
}
```
